version: 2

models:
  - name: bronze_customer_raw
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
      - name: gender
        tests:
          - accepted_values:
              values: ['Male', 'Female']
      - name: _ingested_at
        tests:
          - not_null

  - name: bronze_product_enrollments
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_customer_raw')
              field: customer_id
      - name: product_type
        tests:
          - not_null
          - accepted_values:
              values: ['Savings', 'Credit Card']
      - name: _ingested_at
        tests:
          - not_null

  - name: bronze_crm_interactions
    columns:
      - name: interaction_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_customer_raw')
              field: customer_id
      - name: interaction_type
        tests:
          - not_null
          - accepted_values:
              values: ['Email', 'Chat', 'Call']
      - name: _ingested_at
        tests:
          - not_null

  - name: bronze_transaction_history
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_customer_raw')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_product_enrollments')
              field: product_id
      - name: _ingested_at
        tests:
          - not_null
